import Head from 'next/head'
import About from 'rigo/components/About'
import Contact from 'rigo/components/Contact'
import Main from 'rigo/components/Main'
import Projects from 'rigo/components/Projects'
import Skills from 'rigo/components/Skills'
import Footer from 'rigo/components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rigoberto Estrada Zuniga</title>
        <meta name='description' content='Generated by created next app' />
        <link rel='stylesheet' href='' />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact /> 
    </div>
  )
}
